const MARGIN = {
  SMALL_ICON_TEXT: 4,
  MEDIUM_ICON_TEXT: 6,
  ELEMENT_SPACING: 16,
  BLOCK_SPACING: 32,
  BUTTON_GROUP_SPACING: 44,
  DATE_SPACING: 8,
};

const PADDING = {
  INPUT: 16,
  BUTTON_VERTICAL: 16,
  BUTTON_HORIZONTAL: 32,
};

export default { MARGIN, PADDING, ...MARGIN, ...PADDING };
